### ISSUE TITLE
Usage with socket.io? 

### ISSUE THREAD

**Issue by EwanValentine** [danmactough/node-feedparser#118]
Hi folks,

Great library! Was just wondering if anyone had any examples of using socket.io? 

Currently I'm using the following to emit the data on read ( this is set within ```io.on('connection', function (socket) {};``` ) :

```
feed.on('readable', function() {

		// Set stream item
		var stream = this
		  , meta = this.meta
		  , item;
		
		// While each RSS item
	  	while (item = stream.read()) {

	  		// Emit socket stream
	  		socket.emit('stream', item);
		}
});
```

Here's my reader section:

```
stream.on('response', function(res) {
    var stream = this;
    if (res.statusCode != 200) return this.emit('error', new Error('Bad status code'));
    stream.pipe(feed);
});
```
This streams the data to the page correctly, but I'm not sure how you'd listen for updates on the RSS feed itself? I tried adding setInterval in several places, non seemed to work.

Thanks in advance!

**Comment by Mickael-van-der-Beek** [comment]
If you want to enable push notifications for RSS rather than polling with a setInterval() or cron job, RSS provided the "cloud" tag that does exactly that. Link below:

http://en.wikipedia.org/wiki/RSS_Cloud

I think the question can be closed though since there hasn't been any real activity or follow-up question.

**Comment by danmactough** [comment]
I also recommend @superfeedr http://superfeedr.com/

**Comment by julien51** [comment]
Thanks @danmactough Someday, I have o tell you about our "tracking" feeds :)
