### ISSUE TITLE
node-feedparser + Discord Bot

### ISSUE THREAD

**Issue by Kopertje** [danmactough/node-feedparser#231]
Hello,

Im trying to use node-feedparser to make some RSS feeds in my bot for Discord.
I want to only show a max. of 5 items, now im not a amazing code engineer.. so im looking for some help with this.
How can i achieve this?

Greetings,
Kopertje

**Comment by danmactough** [comment]
This [part of the example](https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js#L30-L35) is where you will have access to each item. Instead of [`console.log`](https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js#L33), if you only want 5, you could push 5 of the items to an array and return that array when parsing is complete, for example.

Hope that helps.
