### ISSUE TITLE
Return date string if it is not in valid JS date format

### ISSUE THREAD

**Issue by Praveena0989** [danmactough/node-feedparser#256]
`feedparser` is returning Invalid date for date string if it is not a valid JS date format but instead of that you can just return the string itself so that there will be room for us to change the date string to right format with site specific rule and convert it back to JS Date.

Example Feed  [rss](http://www.firstpost.com/rss/tech.xml)

**Comment by danmactough** [comment]
@Praveena0989 Yeah, that is really annoying. Feed producers created some terrible, bad stuff. Luckily, in addition to the normalized items like `date` (the "happy path"), the original parsed elements are also available. Since this is an rss feed, each `item` also has the `rss:pubdate` property:

```json
{
 "rss:pubdate": {
    "@": {},
    "#": "Sunday,August 6,2017 13:14 pm"
  }
}
```

So, you can fallback to `item['rss:pubdate']['#']`.

**Comment by Praveena0989** [comment]
Cool. Thank you @danmactough
