### ISSUE TITLE
Synchronous version of library?

### ISSUE THREAD

**Issue by iONinja** [danmactough/node-feedparser#266]
Hi there,

You're library looks really nice, but I would love to be able to syncronously access the parsed feed. Seeing as there's no network or disk I/O, the library's API doesn't _need_ to be asynchronous?

Let me know if this is already a feature, or you're planning to add it. Thank you!

**Comment by scripting** [comment]
I think this may be what you're looking for...

https://github.com/scripting/feedread

I felt as you do -- that all the piping was over-optimizing. For most applications, I just want the data from the feed in a JS object. Which is what feedRead does.

It is not synchronous, because there is I/O involved in reading the feed over the web or from a local file, but inside the callback it's very simple.

Dave

**Comment by danmactough** [comment]
> there is I/O involved in reading the feed over the web or from a local file

Thanks for explaining that so simply @scripting 🙏

**Comment by iONinja** [comment]
Thanks, that's just what I was looking for!
